### ISSUE TITLE
Any plans to contribute this Chatter plugin to Jenkins Community?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [superfell/JenkinsChatterPlugin#7]
SuperFell

I was working with CloudBees support and asked if the could load the Chatter plugin into the list of available Jenkins plugins.  They stated that they are happy to load any "OSS plugins from jenkins community."  CloudBees referenced this "Hosting Plugins" page (https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins) for details on how to make this happen. 

Would you be willing to load this plugin to the Jenkins Community so that it could be available to CloudBees service?

**Comment by superfell** [comment]
Thanks to some sterling work from @sortiz-sfdc the plugin is now available from the central plugin server. The new official repo is at https://github.com/jenkinsci/chatter-notifier-plugin and you can install the current version (2.0.2) from the central plugin list.
